services:
  agent-server:
    volumes:
      - ./src:/app/src

      - ./requirements.txt:/app/requirements.txt
      - ./local-requirements.txt:/app/local-requirements.txt
      - ./local_modules:/app/local_modules

    ports:
      - "8080:80"

  postgres:
    expose:
      - "5432"
    ports:
      - "${COMMAND_SERVER_PORT}:6666"
      - "${DATABASE_PORT}:5432"
    volumes:
      # Persist the data between container invocations
      - postgresVolume:/var/lib/postgresql/data

  data-server:
    ports:
      - "${DATA_SERVER_PORT}:80"
  
  query-server:
    ports:
      - "5001:80"

  redis-query:
    ports:
      - "6379:6379"

  redis-data:
    ports:
      - "6380:6379"
  
  experiment-importer:
    ports:
      - "${EXPERIMENT_IMPORTER_PORT}:80"
    volumes:
      - ./rds-experiments:/data

volumes:
  postgresVolume:
    driver: local